### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kuragehimekurara1** [Creckeryop/3dsCookieClicker#5]
I would like to translate 3DS Cookie Clicker into Japanese. Does 3DS Cookie Clicker support translation?

**Comment by Creckeryop** [comment]
I don't think that's possible

**Comment by kuragehimekurara1** [comment]
Does the PS Vita version of Cookie Clicker support translation?  Are there any plans to support the translation of the 3ds version of cookie clicker in the future?

**Comment by Creckeryop** [comment]
No, really sorry. I don't have any plans to rewrite my old apps. They doesn't support adding new languages. Sorry
